# Generated by Django 3.2.8 on 2021-10-28 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGroupRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('expiration', models.DateTimeField()),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(0, '水'), (1, '食料品'), (2, 'おかず'), (3, 'その他')], help_text='0: 水, 1: 食料品, 2: おかず, 3: その他')),
                ('genre', models.IntegerField(choices=[(0, '水'), (1, '麺'), (2, 'おかゆ'), (3, 'その他')], help_text='0: 水, 1: 麺, 2: おかゆ, 3: その他')),
            ],
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_group_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('count_users', models.IntegerField()),
                ('stock_days', models.IntegerField()),
                ('foods', models.ManyToManyField(through='api.FoodGroupRelation', to='api.FoodModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='users',
            field=models.ManyToManyField(through='api.UserGroupRelation', to='api.UserModel'),
        ),
        migrations.AddField(
            model_name='foodgrouprelation',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodmodel'),
        ),
        migrations.AddField(
            model_name='foodgrouprelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupmodel'),
        ),
    ]
