# Generated by Django 3.2.8 on 2021-10-28 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergrouprelation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usergrouprelation',
            name='user',
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='foods',
            field=models.ManyToManyField(through='api.FoodGroupRelation', to='api.FoodModel'),
        ),
        migrations.RemoveField(
            model_name='groupmodel',
            name='users',
            field=models.ManyToManyField(through='api.UserGroupRelation', to='api.UserModel'),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='foods',
            field=models.ManyToManyField(to='api.FoodModel'),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='users',
            field=models.ManyToManyField(to='api.UserModel'),
        ),
        migrations.DeleteModel(
            name='FoodGroupRelation',
        ),
        migrations.DeleteModel(
            name='UserGroupRelation',
        ),
    ]
